### ISSUE TITLE
Terminal issue

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/ecommerce-pattern-library#2]
@thomasjbradley

This is the error I'm getting now 

Last login: Wed Jan 29 10:02:23 on ttys000
Cherry-Bomb:~ sherithomson$ bundle exec jekyll serve
bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/2.6.0/bin/jekyll)
Gem::Exception: can't find executable jekyll for gem jekyll. jekyll is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:374:in `block in replace_bin_path'
  /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:402:in `block in replace_bin_path'
  /usr/local/lib/ruby/gems/2.6.0/bin/jekyll:23:in `<top (required)>'
Cherry-Bomb:~ sherithomson$

**Comment by sheri-thomson** [comment]
I think I got it! Sorry..
